apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: node-reader
rules:
  - apiGroups: ["", "apiextensions.k8s.io"]
    resources: ["*"]
    verbs: ["*"]