apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-nodes
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd2
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: node-reader
  apiGroup: rbac.authorization.k8s.io