apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  resource.customizations: |
    batch/Job:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = "Proceeding with Job run..."
        if obj.status == nil or obj.status.conditions == nil then
          print(hs.status)
          return hs
        end
        for i, condition in ipairs(obj.status.conditions) do
          if condition.type == "Complete" then
            hs.message = "Job run finished"
            hs.status = "Healthy"
            print(hs.status)
            return hs
          end
          if condition.type == "Failed" then
            hs.message = condition.message
            hs.status = "Degraded"
            print(hs.status)
            return hs
          end
        end
        print(hs.status)
        return hs
    argoproj.io/Application:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        print("app health")
        if obj.status ~= nil then
          local status = obj.status
          if status.conditions ~= nil then
            for i, condition in ipairs(status.conditions) do
              if condition.type ~= nil and string.match(condition.type, '.*Error$') then
                hs.status = "Degraded"
                hs.message = condition.message
                print(hs.status)
                return hs
              end
            end
          end
          if status.health ~= nil then
            local health = status.health
            hs.status = health.status
            if health.message ~= nil then
              hs.message = health.message
            end
            local syncStatus = (status.sync and status.sync.status or nil)
            if hs.status == "Healthy" and syncStatus == "Sync failed" then
              hs.status = "Degraded"
            end
          end
        end
        print(hs.status)
        return hs
