apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: helm-test
spec:
  project: default
  source:
    repoURL: 'https://github.com/larisaad/argo-test.git'
    targetRevision: HEAD
    path: local-helm-application/temp/example-app
    helm:
      releaseName: helm-test
      valueFiles:
        - values-dev.yaml
      ignoreMissingValueFiles: true
      skipCrds: true
  destination:
    server: 127.0.0.1:6443
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
