apiVersion: batch/v1
kind: Job
metadata:
  name: "tests-in-sync-wave-22"
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name | lower }}-tests
          image: busybox
          command: ["/bin/sh"]
          args: ["-c", "echo \"running tests\"; exit 1"]
  backoffLimit: 0
